
# Updated for Azure OpenAI API integration
# Set the following environment variables in your system or CI/CD pipeline:
# - AZURE_OPENAI_API_KEY: Your Azure OpenAI API Key
# - AZURE_OPENAI_ENDPOINT: Your Azure OpenAI Endpoint (e.g., https://<resource-name>.openai.azure.com/)
# - AZURE_OPENAI_API_VERSION: Azure OpenAI API Version (e.g., "2023-03-15-preview")
services:
  app:
    build: .
    environment:
      AZURE_OPENAI_API_KEY: ${AZURE_OPENAI_API_KEY}
      AZURE_OPENAI_API_VERSION: ${AZURE_OPENAI_API_VERSION}
      AZURE_OPENAI_ENDPOINT: ${AZURE_OPENAI_ENDPOINT}
      NEO4J_PASSWORD: Ilovejk@3816
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USERNAME: neo4j
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
    - 8888:8888
    volumes:
    - .:/app
  neo4j:
    environment:
      NEO4JLABS_PLUGINS: '["apoc"]'
      NEO4J_AUTH: neo4j/Ilovejk@3816
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
    image: neo4j:5.18
    ports:
    - 7474:7474
    - 7687:7687
    volumes:
    - neo4j_data:/data
version: '3.8'
volumes:
  neo4j_data: null
