version: '3.8'

services:
  neo4j:
    image: neo4j:5.9.0
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD} # Change the password as needed
    ports:
      - "7474:7474" # Neo4j browser
      - "7687:7687" # Bolt protocol for database
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins

  app:
    build:
      context: .
    container_name: graph_rag_app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEO4J_URI=${NEO4J_URI} 
      - NEO4J_USERNAME=${NEO4J_USERNAME}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD} # Same as the one set in neo4j
    ports:
      - "8888:8888"
    depends_on:
      - neo4j

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins: