
version: '3.8'

services:
  neo4j:
    image: neo4j:5.18
    environment:
      NEO4J_AUTH: neo4j/Ilovejk@3816
      NEO4JLABS_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*"
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: Ilovejk@3816

volumes:
  neo4j_data:
